name: Deploy Worker
# This workflow is responsible for deploying the Worker application to the production environment.

on:
  push:
    branches:
      - main  # The workflow will trigger on pushes to the main branch.

jobs:
  deploy_production:
    runs-on: ubuntu-latest  # The job will run on the latest version of Ubuntu.
    timeout-minutes: 60  # The job will time out after 60 minutes if not completed.
    environment:
      name: production  # Specifies the environment as 'production' for deployment.

    steps:
      - uses: actions/checkout@v4  # Checks out the repository code at the specified version.

      - name: Build & Deploy Worker
        # This step uses the Cloudflare Wrangler Action to build and deploy the Worker.
        uses: cloudflare/wrangler-action@v3
        with:
          wranglerVersion: "3.57.0"  # Specifies the version of Wrangler to use for deployment.
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }} # The API token for authenticating with Cloudflare.
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}  # The Cloudflare account ID for deployment.
          environment: production  # Specifies the environment for the deployment.
